services:
  backend:
    image: security-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data

  create-super-admin:
    image: security-backend
    env_file:
      - ./backend/.env
    volumes:
      - backend_data:/app/data
    command: python scripts/create_super_admin.py
    profiles:
      - admin

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  backend_data:
