"""Maps app module keys to legacy permission codes for API enforcement."""

from __future__ import annotations

from app.rbac import (
    PERM_ALLOW_DELETE,
    PERM_ALLOW_READ,
    PERM_ALLOW_WRITE,
    PERM_ATTEND_READ,
    PERM_ATTEND_WRITE,
    PERM_ASSIGN_DELETE,
    PERM_ASSIGN_READ,
    PERM_ASSIGN_WRITE,
    PERM_CLIENTS_DELETE,
    PERM_CLIENTS_READ,
    PERM_CLIENTS_WRITE,
    PERM_CONTRACTOR_ASSIGN,
    PERM_CONTRACTOR_MANAGE,
    PERM_CONTRACTOR_VIEW,
    PERM_DOC_DELETE,
    PERM_DOC_READ,
    PERM_DOC_WRITE,
    PERM_EMAIL_SEND,
    PERM_EXP_DELETE,
    PERM_EXP_READ,
    PERM_EXP_WRITE,
    PERM_GUARDS_DELETE,
    PERM_GUARDS_READ,
    PERM_GUARDS_WRITE,
    PERM_INCIDENT_READ,
    PERM_INCIDENT_REPORTS,
    PERM_INCIDENT_WRITE,
    PERM_INV_DELETE,
    PERM_INV_READ,
    PERM_INV_WRITE,
    PERM_LEADS_ASSIGN,
    PERM_LEADS_DELETE,
    PERM_LEADS_EXPORT,
    PERM_LEADS_READ,
    PERM_LEADS_REPORTS,
    PERM_LEADS_WRITE,
    PERM_PAY_DELETE,
    PERM_PAY_READ,
    PERM_PAY_WRITE,
    PERM_PAYROLL_READ,
    PERM_PAYROLL_WRITE,
    PERM_PATROL_READ,
    PERM_PATROL_REPORTS,
    PERM_PATROL_SCAN,
    PERM_PATROL_WRITE,
    PERM_PORTAL_HOURS,
    PERM_PORTAL_ROTA_CURRENT,
    PERM_PORTAL_ROTA_PREVIOUS,
    PERM_PORTAL_ROTA_UPCOMING,
    PERM_PORTAL_SITES,
    PERM_RATES_DELETE,
    PERM_RATES_READ,
    PERM_RATES_WRITE,
    PERM_REP_READ,
    PERM_ROLES_DELETE,
    PERM_ROLES_READ,
    PERM_ROLES_WRITE,
    PERM_ROTA_CREATE,
    PERM_ROTA_DELETE,
    PERM_ROTA_EDIT,
    PERM_ROTA_VIEW,
    PERM_SITES_DELETE,
    PERM_SITES_READ,
    PERM_SITES_WRITE,
    PERM_STAFF_REQ_READ,
    PERM_STAFF_REQ_REVIEW,
    PERM_STAFF_REQ_WRITE,
    PERM_SUB_MANAGE,
    PERM_SUB_READ,
    PERM_SUBS_DELETE,
    PERM_SUBS_READ,
    PERM_SUBS_WRITE,
)

# Per app module key: action -> legacy permission codes granted to the user/token
MODULE_LEGACY_EXPANSION: dict[str, dict[str, frozenset[str]]] = {
    "dashboard": {
        "view": frozenset({PERM_GUARDS_READ}),
    },
    "guards": {
        "view": frozenset({PERM_GUARDS_READ}),
        "create": frozenset({PERM_GUARDS_WRITE}),
        "edit": frozenset({PERM_GUARDS_WRITE}),
        "delete": frozenset({PERM_GUARDS_DELETE}),
    },
    "documents": {
        "view": frozenset({PERM_DOC_READ}),
        "create": frozenset({PERM_DOC_WRITE}),
        "edit": frozenset({PERM_DOC_WRITE}),
        "delete": frozenset({PERM_DOC_DELETE}),
    },
    "contractors": {
        "view": frozenset({PERM_SUBS_READ, PERM_CONTRACTOR_VIEW}),
        "create": frozenset({PERM_SUBS_WRITE, PERM_CONTRACTOR_MANAGE}),
        "edit": frozenset({PERM_SUBS_WRITE, PERM_CONTRACTOR_MANAGE, PERM_CONTRACTOR_ASSIGN}),
        "delete": frozenset({PERM_SUBS_DELETE, PERM_CONTRACTOR_MANAGE}),
    },
    "sub_contractors": {
        "view": frozenset({PERM_SUBS_READ, PERM_CONTRACTOR_VIEW}),
        "create": frozenset({PERM_SUBS_WRITE, PERM_CONTRACTOR_MANAGE}),
        "edit": frozenset({PERM_SUBS_WRITE, PERM_CONTRACTOR_MANAGE}),
        "delete": frozenset({PERM_SUBS_DELETE, PERM_CONTRACTOR_MANAGE}),
    },
    "attendance": {
        "view": frozenset({PERM_ATTEND_READ}),
        "create": frozenset({PERM_ATTEND_WRITE}),
        "edit": frozenset({PERM_ATTEND_WRITE}),
        "delete": frozenset({PERM_ATTEND_WRITE}),
    },
    "roles": {
        "view": frozenset({PERM_ROLES_READ}),
        "create": frozenset({PERM_ROLES_WRITE}),
        "edit": frozenset({PERM_ROLES_WRITE}),
        "delete": frozenset({PERM_ROLES_DELETE}),
    },
    "my_portal": {
        "view": frozenset({PERM_PORTAL_SITES, PERM_PORTAL_ROTA_CURRENT, PERM_PORTAL_HOURS}),
        "create": frozenset({PERM_PORTAL_ROTA_UPCOMING}),
        "edit": frozenset({PERM_PORTAL_ROTA_PREVIOUS}),
    },
    "sites": {
        "view": frozenset({PERM_SITES_READ}),
        "create": frozenset({PERM_SITES_WRITE}),
        "edit": frozenset({PERM_SITES_WRITE}),
        "delete": frozenset({PERM_SITES_DELETE}),
    },
    "assignments": {
        "view": frozenset({PERM_ROTA_VIEW, PERM_ASSIGN_READ}),
        "create": frozenset({PERM_ROTA_CREATE, PERM_ASSIGN_WRITE}),
        "edit": frozenset({PERM_ROTA_EDIT, PERM_ASSIGN_WRITE}),
        "delete": frozenset({PERM_ROTA_DELETE, PERM_ASSIGN_DELETE}),
    },
    "rota": {
        "view": frozenset({PERM_ROTA_VIEW, PERM_ASSIGN_READ, PERM_ATTEND_READ}),
        "create": frozenset({PERM_ROTA_CREATE, PERM_ASSIGN_WRITE}),
        "edit": frozenset({PERM_ROTA_EDIT, PERM_ASSIGN_WRITE, PERM_ATTEND_WRITE}),
        "delete": frozenset({PERM_ROTA_DELETE, PERM_ASSIGN_DELETE}),
    },
    "patrol": {
        "view": frozenset({PERM_PATROL_READ, PERM_PATROL_REPORTS}),
        "create": frozenset({PERM_PATROL_WRITE}),
        "edit": frozenset({PERM_PATROL_WRITE, PERM_PATROL_SCAN}),
        "delete": frozenset({PERM_PATROL_WRITE}),
    },
    "incidents": {
        "view": frozenset({PERM_INCIDENT_READ, PERM_INCIDENT_REPORTS}),
        "create": frozenset({PERM_INCIDENT_WRITE}),
        "edit": frozenset({PERM_INCIDENT_WRITE}),
        "delete": frozenset({PERM_INCIDENT_WRITE}),
    },
    "accident_reports": {
        "view": frozenset({PERM_INCIDENT_READ}),
        "create": frozenset({PERM_INCIDENT_WRITE}),
        "edit": frozenset({PERM_INCIDENT_WRITE}),
        "delete": frozenset({PERM_INCIDENT_WRITE}),
    },
    "client_portal": {
        "view": frozenset({PERM_STAFF_REQ_READ}),
        "create": frozenset({PERM_STAFF_REQ_WRITE}),
        "edit": frozenset({PERM_STAFF_REQ_WRITE}),
        "delete": frozenset({PERM_STAFF_REQ_REVIEW}),
    },
    "staff_requests": {
        "view": frozenset({PERM_STAFF_REQ_READ}),
        "create": frozenset({PERM_STAFF_REQ_WRITE}),
        "edit": frozenset({PERM_STAFF_REQ_REVIEW}),
        "delete": frozenset({PERM_STAFF_REQ_REVIEW}),
    },
    "clients": {
        "view": frozenset({PERM_CLIENTS_READ}),
        "create": frozenset({PERM_CLIENTS_WRITE}),
        "edit": frozenset({PERM_CLIENTS_WRITE}),
        "delete": frozenset({PERM_CLIENTS_DELETE}),
    },
    "leads": {
        "view": frozenset({PERM_LEADS_READ, PERM_LEADS_REPORTS, PERM_LEADS_EXPORT}),
        "create": frozenset({PERM_LEADS_WRITE, PERM_LEADS_ASSIGN}),
        "edit": frozenset({PERM_LEADS_WRITE, PERM_LEADS_ASSIGN}),
        "delete": frozenset({PERM_LEADS_DELETE}),
    },
    "payroll": {
        "view": frozenset({PERM_PAYROLL_READ}),
        "create": frozenset({PERM_PAYROLL_WRITE}),
        "edit": frozenset({PERM_PAYROLL_WRITE}),
        "delete": frozenset({PERM_PAYROLL_WRITE}),
    },
    "invoices": {
        "view": frozenset({PERM_INV_READ}),
        "create": frozenset({PERM_INV_WRITE}),
        "edit": frozenset({PERM_INV_WRITE}),
        "delete": frozenset({PERM_INV_DELETE}),
    },
    "payments": {
        "view": frozenset({PERM_PAY_READ}),
        "create": frozenset({PERM_PAY_WRITE}),
        "edit": frozenset({PERM_PAY_WRITE}),
        "delete": frozenset({PERM_PAY_DELETE}),
    },
    "expenses": {
        "view": frozenset({PERM_EXP_READ}),
        "create": frozenset({PERM_EXP_WRITE}),
        "edit": frozenset({PERM_EXP_WRITE}),
        "delete": frozenset({PERM_EXP_DELETE}),
    },
    "allowances": {
        "view": frozenset({PERM_ALLOW_READ}),
        "create": frozenset({PERM_ALLOW_WRITE}),
        "edit": frozenset({PERM_ALLOW_WRITE}),
        "delete": frozenset({PERM_ALLOW_DELETE}),
    },
    "reports": {
        "view": frozenset({PERM_REP_READ}),
        "create": frozenset({PERM_REP_READ}),
        "edit": frozenset({PERM_REP_READ}),
        "delete": frozenset({PERM_REP_READ}),
    },
    "company": {
        "view": frozenset({PERM_SUB_READ}),
        "create": frozenset({PERM_SUB_MANAGE}),
        "edit": frozenset({PERM_SUB_MANAGE, PERM_RATES_WRITE}),
        "delete": frozenset({PERM_SUB_MANAGE}),
    },
    "billing": {
        "view": frozenset({PERM_SUB_READ}),
        "create": frozenset({PERM_SUB_MANAGE}),
        "edit": frozenset({PERM_SUB_MANAGE}),
        "delete": frozenset({PERM_SUB_MANAGE}),
    },
    "special_days": {
        "view": frozenset({PERM_ALLOW_READ}),
        "create": frozenset({PERM_ALLOW_WRITE}),
        "edit": frozenset({PERM_ALLOW_WRITE}),
        "delete": frozenset({PERM_ALLOW_DELETE}),
    },
    "sms": {
        "view": frozenset({PERM_EMAIL_SEND}),
        "create": frozenset({PERM_EMAIL_SEND}),
        "edit": frozenset({PERM_EMAIL_SEND}),
        "delete": frozenset({PERM_EMAIL_SEND}),
    },
    "email_settings": {
        "view": frozenset({PERM_EMAIL_SEND}),
        "create": frozenset({PERM_EMAIL_SEND}),
        "edit": frozenset({PERM_EMAIL_SEND}),
        "delete": frozenset({PERM_EMAIL_SEND}),
    },
}


def legacy_codes_for_module_action(module_key: str, action: str) -> frozenset[str]:
    mod = MODULE_LEGACY_EXPANSION.get(module_key, {})
    return mod.get(action, frozenset())
